baseurl = "http://thleap.net/"
title = "thleap.net"
languageCode = "ja"
Paginate = 12
publishdir = "_public"

[[menu.global]]
    name = "Blog"
    identifier = "blog"
    weight = 0
    url = "/blog/"
[[menu.global]]
    name = "Work"
    identifier = "work"
    weight = 1
    url = "/work/"
[[menu.global]]
    name = "About"
    identifier = "about"
    weight = 2
    url = "/about/"
